### ISSUE TITLE
Refresh page after cookies has been accepted

### ISSUE THREAD

**Issue by Hesesses** [doublethreedigital/cookie-notice#39]
Hello,

I know the statamic v2 version is not updated anymore, but i'm still asking could it be possible to have a feature to refresh the page when cookies has been accepted by the user. 

For example we have chat on our site and would be nice to be able to display that right after cookies has been accepted. Currently it needs a new page load

**Comment by duncanmcclean** [comment]
Like you mentioned, the v2 version of this addon is no longer supported, apart for security updates.

Because it's unlikely any further updates are going to be issued, you should be able to modify the addon code youself to add it in.

Inside the `site/addons/CookieNotice/resources/views/notice.blade.php` file and in the `consentWithCookies` function, you can add a window reload, like so:

```js
function consentWithCookies() {
    setCookie('{{ $cookieName }}', COOKIE_VALUE, '365 * 20'); 
    hideCookieDialog();
}
```

Hopefully that will do the trick! Let me know how you get on.
